#!/usr/bin/env bash

{% if not bitmap %}
battery () {
	battery="$(</sys/class/power_supply/BAT0/capacity)"
	charging="$(</sys/class/power_supply/BAT0/status)"

	case "$battery" in
		[0-9]|10)
			battery="${battery}%  "
		;;

		1[0-9]|2[0-5])
			battery="${battery}%  "
		;;

		2[6-9]|3[0-9]|4[0-9]|50)
			battery="${battery}%  "
		;;

		5[1-9]|6[0-9]|7[0-5])
			battery="${battery}%  "
		;;

		7[6-9]|8[0-9]|9[0-9]|100)
			battery="${battery}%  "
		;;
	esac

	[ "$charging" == "Charging" ] && \
		battery="Charging  $battery"

	printf "%s" "$battery   "
}
{% else %}
battery () {
	battery="$(</sys/class/power_supply/BAT0/capacity)"
	charging="$(</sys/class/power_supply/BAT0/status)"

	case "$battery" in
		[0-9]|10)
			battery="${battery}%  "
		;;

		1[0-9]|2[0-5])
			battery="${battery}%  "
		;;

		2[6-9]|3[0-9]|4[0-9]|50)
			battery="${battery}%  "
		;;

		5[1-9]|6[0-9]|7[0-5])
			battery="${battery}%  "
		;;

		7[6-9]|8[0-9]|9[0-9]|100)
			battery="${battery}%  "
		;;
	esac

	[ "$charging" == "Charging" ] && \
		battery="Charging  $battery"

	printf "%s" "$battery   "
}
{% endif %}
battery
