#!/usr/bin/env bash

pkill admiral &>/dev/null
pkill lemonbar &>/dev/null

$HOME/.local/bin/admiral | lemonbar -p -B "#{{ baralpha }}{{ barback }}" -F "{{ bartext }}" -f "{{ barfont }}:size=7" -f "FontAwesome:size=8" -f "Siji-7" -f "Symbola-8" -g 1920x18+0+0 | sh
