#!/usr/bin/env python3

import i3ipc

# Create the Connection object that can be used to send commands and subscribe
# to events.
i3 = i3ipc.Connection()
coloractive = '{{ '%{' }}{% if not barbars %}F{% else %}U{% endif %}{{ barfoc }}{{ '}' }}'
colorinactive = '{{ '%{' }}{% if not barbars %}F{% else %}U{% endif %}{{ barunfoc }}{{ '}' }}'
colorwarning = '{{ '%{' }}{% if not barbars %}F{% else %}U{% endif %}{{ warning }}{{ '}' }}'

# Define a callback to be called when you switch workspaces.
def on_workspace_focus(self, e):
    workspace_string = '    '
    workspaces = i3.get_workspaces()

    ws_nums = [int(n['num']) for n in workspaces]
    focused = [n['visible'] for n in workspaces].index(True)
    urg = [n for n, _ in enumerate(workspaces) if workspaces[n]['urgent'] == True]
    names ={% if not diffname %}[''.join([i for i in n['name'] if not i.isdigit()]) for n in workspaces]{% else %}len(ws_nums)*['{{ diffws }}']{% endif %}

    for n in range(len(ws_nums)):
        if focused == n:
            workspace_string += coloractive + {% if not barbars %}names[n]{% else %}{{ '\'%{+u}' + barbarwid + '%{-u}%{U-}\'' }}{% endif %} + '{{ wspaces }}'
        elif n in urg:
            workspace_string += colorwarning + {% if not barbars%}names[n]{% else %}{{ '\'%{+u}' + barbarwid + '%{-u}%{U-}\'' }}{% endif %} + '{{ wspaces }}'
        else:
            workspace_string += colorinactive + {% if not barbars%}names[n]{% else %}{{ '\'%{+u}' + barbarwid + '%{-u}%{U-}\'' }}{% endif %} + '{{ wspaces }}'

    print(workspace_string, flush=True)

workspace_string = '    '
workspaces = i3.get_workspaces()

ws_nums = [int(n['num']) for n in workspaces]
focused = [n['visible'] for n in workspaces].index(True)
urg = [n for n, _ in enumerate(workspaces) if workspaces[n]['urgent'] == True]
names ={% if not diffname %}[''.join([i for i in n['name'] if not i.isdigit()]) for n in workspaces]{% else %}len(ws_nums)*['{{ diffws }}']{% endif %}

for n in range(len(ws_nums)):
    if focused == n:
        workspace_string += coloractive + {% if not barbars%}names[n]{% else %}{{ '\'%{+u}' + barbarwid + '%{-u}%{U-}\'' }}{% endif %} + '{{ wspaces }}'
    elif n in urg:
        workspace_string += colorwarning + {% if not barbars%}names[n]{% else %}{{ '\'%{+u}' + barbarwid + '%{-u}%{U-}\'' }}{% endif %} + '{{ wspaces }}'
    else:
        workspace_string += colorinactive + {% if not barbars%}names[n]{% else %}{{ '\'%{+u}' + barbarwid + '%{-u}%{U-}\'' }}{% endif %} + '{{ wspaces }}'

print(workspace_string, flush=True)

# Subscribe to events
i3.on('workspace', on_workspace_focus)

# Start the main loop and wait for events to come in.
i3.main()
